export const dummyData = [
  {
    id: 3,
    date: 'Mar 2020',
    list_names: 'Centimia',
    enteries: null,
    details: null,
  },
  {
    id: 4,
    date: 'Feb 2020',
    list_names: 'Rhyloo',
    enteries: null,
    details: null,
  },
  {
    id: 7,
    date: 'Jul 2019',
    list_names: 'Photofeed',
    enteries: null,
    details: null,
  },
  {
    id: 1,
    date: 'Jul 2019',
    list_names: 'Trudeo Sharable foreground open architecture',
    enteries: 23,
    details: 'Sharable foreground open architecture',
  },
  {
    id: 2,
    date: 'Dec 2019',
    list_names: 'Blogpad',
    enteries: 100,
    details: 'Decentralized disintermediate methodology',
  },
  {
    id: 5,
    date: 'Jan 2020',
    list_names: 'Yakitri',
    enteries: 58,
    details: 'Business-focused value-added solution',
  },
  {
    id: 6,
    date: 'Nov 2019',
    list_names: 'Roomm',
    enteries: 40,
    details: 'Ergonomic static complexity',
  },
  {
    id: 8,
    date: 'Jul 2019',
    list_names: 'Aivee',
    enteries: null,
    details: null,
  },
  {
    id: 9,
    date: 'Jun 2019',
    list_names: 'Meedoo',
    enteries: 63,
    details: 'Progressive logistical Graphical User Interface',
  },
  {
    id: 10,
    date: 'Jun 2019',
    list_names: 'Riffpath',
    enteries: 37,
    details: 'Visionary asymmetric policy',
  },
  {
    id: 11,
    date: 'Dec 2019',
    list_names: 'Omba',
    enteries: null,
    details: null,
  },
  {
    id: 12,
    date: 'Mar 2020',
    list_names: 'Jamia',
    enteries: 67,
    details: 'Multi-lateral solution-oriented approach',
  },
  {
    id: 13,
    date: 'Sep 2019',
    list_names: 'Cogibox',
    enteries: 66,
    details: 'Balanced mission-critical secured line',
  },
  {
    id: 14,
    date: 'Nov 2019',
    list_names: 'Quatz',
    enteries: 82,
    details: 'Synchronised multi-tasking middleware',
  },
  {
    id: 15,
    date: 'Jun 2019',
    list_names: 'Dynava',
    enteries: 75,
    details: 'Public-key interactive infrastructure',
  },
  {
    id: 16,
    date: 'Jun 2019',
    list_names: 'Omba',
    enteries: 23,
    details: 'Realigned non-volatile budgetary management',
  },
  {
    id: 17,
    date: 'Jan 2020',
    list_names: 'Shufflester',
    enteries: 100,
    details: 'Devolved needs-based process improvement',
  },
  {
    id: 18,
    date: 'Oct 2019',
    list_names: 'Flashspan',
    enteries: null,
    details: null,
  },
  {
    id: 19,
    date: 'Jun 2019',
    list_names: 'Twitterlist',
    enteries: 7,
    details: 'Business-focused system-worthy project',
  },
  {
    id: 20,
    date: 'Apr 2020',
    list_names: 'Eamia',
    enteries: 67,
    details: 'Managed logistical policy',
  },
  {
    id: 21,
    date: 'Oct 2019',
    list_names: 'Demimbu',
    enteries: 97,
    details: 'Proactive global extranet',
  },
  {
    id: 22,
    date: 'Aug 2019',
    list_names: 'Voomm',
    enteries: 37,
    details: 'Cross-platform incremental challenge',
  },
  {
    id: 23,
    date: 'Sep 2019',
    list_names: 'Blogpad',
    enteries: 40,
    details: 'Enterprise-wide zero tolerance framework',
  },
  {
    id: 24,
    date: 'Sep 2019',
    list_names: 'Abata',
    enteries: 99,
    details: 'Compatible mobile data-warehouse',
  },
  {
    id: 25,
    date: 'Jul 2019',
    list_names: 'Pixoboo',
    enteries: null,
    details: null,
  },
  {
    id: 26,
    date: 'Aug 2019',
    list_names: 'Edgeblab',
    enteries: 17,
    details: 'Digitized explicit product',
  },
  {
    id: 27,
    date: 'Dec 2019',
    list_names: 'Kwideo',
    enteries: 81,
    details: 'Automated foreground matrix',
  },
  {
    id: 28,
    date: 'Sep 2019',
    list_names: 'Skyvu',
    enteries: 97,
    details: 'Right-sized leading edge open architecture',
  },
  {
    id: 29,
    date: 'Dec 2019',
    list_names: 'Lajo',
    enteries: 66,
    details: 'Assimilated incremental circuit',
  },
  {
    id: 30,
    date: 'Dec 2019',
    list_names: 'Bubblebox',
    enteries: 8,
    details: 'Streamlined dynamic protocol',
  },
  {
    id: 31,
    date: 'Oct 2019',
    list_names: 'Roombo',
    enteries: 43,
    details: 'Horizontal cohesive application',
  },
  {
    id: 32,
    date: 'Jul 2019',
    list_names: 'Voonder',
    enteries: 61,
    details: 'Adaptive holistic focus group',
  },
  {
    id: 33,
    date: 'Sep 2019',
    list_names: 'Tavu',
    enteries: 32,
    details: 'Progressive dedicated workforce',
  },
  {
    id: 34,
    date: 'Jan 2020',
    list_names: 'Pixonyx',
    enteries: 9,
    details: 'Seamless incremental knowledge user',
  },
  {
    id: 35,
    date: 'Dec 2019',
    list_names: 'Eazzy',
    enteries: 48,
    details: 'Pre-emptive attitude-oriented product',
  },
  {
    id: 36,
    date: 'Sep 2019',
    list_names: 'Brainsphere',
    enteries: 18,
    details: 'Reactive optimizing groupware',
  },
  {
    id: 37,
    date: 'Dec 2019',
    list_names: 'Blogspan',
    enteries: 54,
    details: 'Profit-focused even-keeled hub',
  },
  {
    id: 38,
    date: 'Oct 2019',
    list_names: 'Bluejam',
    enteries: 52,
    details: 'Synchronised interactive complexity',
  },
  {
    id: 39,
    date: 'May 2020',
    list_names: 'Twitterbeat',
    enteries: 34,
    details: 'Self-enabling bifurcated task-force',
  },
  {
    id: 40,
    date: 'Mar 2020',
    list_names: 'Kaymbo',
    enteries: null,
    details: null,
  },
  {
    id: 41,
    date: 'Sep 2019',
    list_names: 'Brainbox',
    enteries: 54,
    details: 'Seamless executive toolset',
  },
  {
    id: 42,
    date: 'Nov 2019',
    list_names: 'Bluejam',
    enteries: 28,
    details: 'Adaptive real-time toolset',
  },
  {
    id: 43,
    date: 'May 2020',
    list_names: 'Mudo',
    enteries: 33,
    details: 'Multi-channelled dedicated firmware',
  },
  {
    id: 44,
    date: 'Feb 2020',
    list_names: 'Dynabox',
    enteries: 59,
    details: 'Front-line web-enabled policy',
  },
  {
    id: 45,
    date: 'May 2020',
    list_names: 'Twimm',
    enteries: 61,
    details: 'Networked 5th generation challenge',
  },
  {
    id: 46,
    date: 'Sep 2019',
    list_names: 'Roombo',
    enteries: null,
    details: null,
  },
  {
    id: 47,
    date: 'Feb 2020',
    list_names: 'Chatterbridge',
    enteries: 84,
    details: 'Polarised fresh-thinking support',
  },
  {
    id: 48,
    date: 'Jun 2019',
    list_names: 'Bluezoom',
    enteries: 100,
    details: 'Integrated optimizing forecast',
  },
  {
    id: 49,
    date: 'Sep 2019',
    list_names: 'Youbridge',
    enteries: 52,
    details: 'Organized bandwidth-monitored synergy',
  },
  {
    id: 50,
    date: 'Jul 2019',
    list_names: 'Agimba',
    enteries: 11,
    details: 'Enhanced exuding hub',
  },
];
